### ISSUE TITLE
安装时报错处理

### ISSUE THREAD

**Issue by wei98k** [oygza/aliyun-php-sdk-afs#1]
确认仓库地址配置为: https://packagist.laravel-china.org  如何使用的是 https://pkg.phpcomposer.com 可能会出现下面错误. 所有安装包（zip）以及元数据（json）进行校验和修复. 2018年09月13日11:01:35 止还是不可用. 

执行: `composer require oygza/aliyun-php-sdk-afs` 显示下面错误
```
 [InvalidArgumentException]
  Could not find a version of package oygza/aliyun-php-sdk-afs matching your minimum-stability (dev). Require it with an explicit vers
  ion constraint allowing its desired stability.
```
执行: `composer require oygza/aliyun-php-sdk-afs=1.0.0` 显示下面错误
```
  [InvalidArgumentException]
  Could not find package oygza/aliyun-php-sdk-afs.

  Did you mean this?
      oygza/aliyun-php-sdk-afs
```
查看: composer config -l
```
[repositories.packagist.org.url] https://packagist.phpcomposer.com
```
重新配置仓库地址-使用全局配置 https://packagist.laravel-china.org
```
composer config -g repo.packagist composer https://packagist.laravel-china.org
```

**Comment by 9r65** [comment]
感谢! , https://pkg.phpcomposer.com这个镜像一直没有后续更新 
已经补充在Readme中
