### ISSUE TITLE
DefaultProfile not found 

### ISSUE THREAD

**Issue by wei98k** [oygza/aliyun-php-sdk-afs#2]
```
use src/aliyun/core
... 
$iClientProfile = DefaultProfile::getProfile ("cn-hangzhou", "ACCESSKEY", "ACCESS_SECRET");
...
```
运行代码报错

```
Class 'DefaultProfile' not found"
```

**Comment by 9r65** [comment]
额  aliyun-core这个库移植过来时没有做任何处理, 原sdk库( 可能考虑到兼容性问题 ) 并没有使用命名空间和遵循Psr-4中的自动加载 , 所以aliyun-core这个库依赖于composer中的 classmap属性引入进来 .
所以如果将core从这个封装类中剥离 需要手动引入文件 , 否则只需要引入composer中的autoload文件, 即可使用

**Comment by wei98k** [comment]
@oygza  我这样直接用 \ 就可以使用. 就不会报错误. 
```
\ $iClientProfile = DefaultProfile::getProfile ("cn-hangzhou", "ACCESSKEY", "ACCESS_SECRET");
```

**Comment by 9r65** [comment]
@helloMJW  抱歉 没太了解这段代码
```php
\ $iClientProfile = DefaultProfile::getProfile ("cn-hangzhou", "ACCESSKEY", "ACCESS_SECRET");

```
这样不会报编译错误嘛 ? 
你是在框架中引入这个库嘛 ?

**Comment by wei98k** [comment]
@oygza  
写错了, 应该是这样.   是的 我想在Laravel中使用这个库. 
```
$iClientProfile = \ DefaultProfile::getProfile ("cn-hangzhou", "ACCESSKEY", "ACCESS_SECRET");
```

**Comment by helloMJW** [comment]
@oygza  
写错了, 应该是这样.   是的 我想在Laravel中使用这个库. 
```
$iClientProfile = \ DefaultProfile::getProfile ("cn-hangzhou", "ACCESSKEY", "ACCESS_SECRET");
```

**Comment by 9r65** [comment]
我刚才在这个laravel 5.5 版本中试了一下 , 使用起来没有问题 . 在我引入composer中 , IDE已经可以自动补全该库了 ( 使用phpstorm ) , 当然也有可能无法补全 ,可以先尝试一下 **composer update** 后再试, 也可以尝试在改类名前加上 **\** 让php自己全局查找这个类 , 使用起来没什么区别

**Comment by oygza** [comment]
上条少写了 应该是 : 

>  在改类名前加上 **/** 让php自己全局查找这个类

**Comment by 9r65** [comment]
上条被markdown和谐了 应该是: 

> 在改类名前加上 \ 让php自己全局查找这个类

**Comment by wei98k** [comment]
> @oygza
> 写错了, 应该是这样. 是的 我想在Laravel中使用这个库.
> 
> ```
> $iClientProfile = \ DefaultProfile::getProfile ("cn-hangzhou", "ACCESSKEY", "ACCESS_SECRET");
> ```

那就是我这种写法了, 就是这个包是不需要使用use引用的, 而是直接使用全局方式`\` 这个符号.
